### ISSUE TITLE
get_library_information is not implemented

### ISSUE THREAD

**Issue by mardukbp** [robotframework/jrobotremoteserver#58]
When importing a Remote library served by JRobotRemoteServer I get the following error: 

```
ERROR org.apache.xmlrpc.server.XmlRpcErrorLogger - No such handler: get_library_information
```

The `get_library_information` method was introduced in Robot Framework 4.0.

**Comment by pekkaklarck** [comment]
This is a pretty new remote API method and it's not a surprise many remote servers don't implement it yet. Where do you see that error? I wonder if the Remote library itself could do something to avoid it.

**Comment by mardukbp** [comment]
It seems to me that the Remote library is calling this method. The exception is thrown when I run the following test:

```robot
*** Settings ***
Library    Remote    http://127.0.0.1:1111/test

*** Test Cases ***
Salute
    Say Hello To    Marduk
```

Here is the exception from the Java remote server:

```
11:08:05.852 [qtp825962150-16] ERROR org.apache.xmlrpc.server.XmlRpcErrorLogger - No such handler: get_library_information
org.apache.xmlrpc.server.XmlRpcNoSuchHandlerException: No such handler: get_library_information
```

**Comment by GerwinLaagland** [comment]
A question on whether there's any progress on this front. Currently the developer that uses this plugin for the java library we have at my current assignment is moving to supress the call in order to avoid stacktraces being generated. As already mentioned the origin of it is that RF4.x is requesting by using the get_library_information handler. 

Hopefully this will help, but it's probably much better to just handle it in the remote library.. or in here.

This issue also seems to cause some unwanted side effects such as performance being hampered before Robot has imported the keywords from the java library. Currently the robotcode VSCode plugin that I have been using (see linked issue earlier) measures 30 seconds delay at minimum... for every file that I open in VSCode related to this library.

A short summary:
- For each time a testcase is being run with the library a null pointer will be generated in the server log
- For every diagnostic being run on files that open with VSCode / Robotcode plugin a delay of 30 seconds as it is (presumably) waiting for a response on this call

Admittedly I can't quite exclude one from the other so I've raised the issue at the plugin owner as well. But it does seem all related. Thanks in advance for the info that any of you can provide!

**Comment by Hannu1** [comment]
I fixed this in our project by inheriting ServerMethods class and adding public method:
```java
public Map<String, Object> get_library_information() {
    return get_keyword_names().stream().map(k->new AbstractMap.SimpleEntry<>(k, getLibraryInformation(k)))
            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
}

private Object getLibraryInformation(String keyword) {
    Map<String, Object> info = new HashMap<>();
    info.put("args", get_keyword_arguments(keyword));
    info.put("types", get_keyword_types(keyword));
    info.put("tags", get_keyword_tags(keyword));
    info.put("doc", get_keyword_documentation(keyword));
    return info;
}
```
I had to override/copy paste other stuff in order to change ServerMethods implementation though. I can make a pull request, if this is an acceptable fix.

**Comment by pekkaklarck** [comment]
This project doesn't seem to be actively maintained at the moment. Do you @Hi-Fi or @ombre42 have time/interested towards it? Are there any new people interested to help?

It would probably be a good idea to move this project to make it easier for the community to collaborate.

**Comment by Hi-Fi** [comment]
Agree that moving to Marketsquare would make sense. Also if there is fix available, PR would be welcome also to this repo.

@pekkaklarck I don't have enough rights at robotframework organization side to make the move, maybe you can?

**Comment by Hannu1** [comment]
@Hi-Fi  there's an issue with the fix. stop_remote_server keyword which is added by ServerMethods causes another exception later (duplicate keyword stop_remote_server).

I was able to circumvent this by filtering out stop_remote_server in get_library_information method:
```java
public Map<String, Object> get_library_information() {
    return get_keyword_names().stream().filter(k->!"stop_remote_server".equals(k)).map(k->new AbstractMap.SimpleEntry<>(k, getLibraryInformation(k)))
            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
}
```

**Comment by Hannu1** [comment]
I can only say filtering it out works for us, but we do not use or allow stop_remote_server keyword. 

Tests hang (without any changes) on robot framework 4.1.2 and 4.0.3 (tried different robot-maven-plugin versions as well), so I can't run the tests for this.

**Comment by Hi-Fi** [comment]
Hmm... Have to check code out myself, as for some reason actions are not even offered to run with that PR.

**Comment by Hi-Fi** [comment]
@mardukbp @GerwinLaagland Are you still experiencing the issue with (just release) 4.1.0? At least included test project was passing, but not sure if it tested the exact issue. 

`get_library_information` itself was implemented by @Hannu1, and in release also dependencies were updated.

**Comment by GerwinLaagland** [comment]
Hello @Hi-Fi, I can't confirm if the problem persists. A java developer was so kind to repair the problem on their side. I will check with him to see if the new version of the remote server does the things he requires.  

The problem has been resolved by us client side in the java code. So the urgency was dropped considerably. In any case thanks for your assistance in this manner! It is much appreciated.
